
function loadData(){ return fetch('data.json').then(r=>r.json()); }

function renderJornadaList(){ loadData().then(db=>{ const ul=document.getElementById('jornadasList'); if(!ul) return; ul.innerHTML=''; db.jornadas.forEach(j=>{ const li=document.createElement('li'); const a=document.createElement('a'); a.href='jornada.html?id='+j.id; a.innerText='Jornada '+j.id+' - '+(j.fecha||j.nombre||''); li.appendChild(a); ul.appendChild(li); }); }); }

function renderJornadaById(){ const params=new URLSearchParams(location.search); const id=params.get('id')||'1'; loadData().then(db=>{ const j=db.jornadas.find(x=>String(x.id)===String(id)); if(!j) return; const matches=document.getElementById('matches'); matches.innerHTML='<ol>'+Object.values(j.partidos).map(s=>'<li>'+s+'</li>').join('')+'</ol>'; const table=document.getElementById('table'); let html='<table class="pron-table"><thead><tr><th>Jugador</th>'; for(let i=1;i<=14;i++) html+='<th>'+i+'</th>'; html+='<th>Aciertos</th></tr></thead><tbody>'; const meta=j.meta||{}; const worst=meta.worst, second_worst=meta.second_worst, best=meta.best; db.players.forEach(p=>{ const u=p.username; const ac = j.aciertos && j.aciertos[u] ? j.aciertos[u] : 0; let rowClass=''; if(u===worst) rowClass='worst'; else if(u===second_worst) rowClass='second-worst'; else if(u===best) rowClass='best'; html+='<tr class="'+rowClass+'"><td>'+u+'</td>'; for(let i=1;i<=14;i++){ const val = j.pronosticos[u] ? j.pronosticos[u][String(i)] : ''; html+='<td>'+(val||'')+'</td>'; } html+='<td>'+ac+'</td></tr>'; }); html+='</tbody></table>'; table.innerHTML=html; }); }

function renderMyPron(){ loadData().then(db=>{ const user=localStorage.getItem('jugadorActivo'); const out=document.getElementById('mypron'); if(!out) return; if(!user){ out.innerHTML='Inicia sesión'; return;} const j=db.jornadas[0]; let html='<form id="myForm"><table class="edit-table"><tr><th>Partido</th><th>Tu pronóstico</th></tr>'; for(let i=1;i<=14;i++){ const val = j.pronosticos[user] ? j.pronosticos[user][String(i)] : ''; html+='<tr><td>'+j.partidos[String(i)]+'</td><td><select name="'+i+'"><option value="">--</option><option value="1">1</option><option value="X">X</option><option value="2">2</option></select></td></tr>'; } html+='</table></form>'; out.innerHTML=html; document.getElementById('saveBtn')?.addEventListener('click', saveMyPron); }); }

function saveMyPron(){ const form=document.getElementById('myForm'); const data={}; for(let i=1;i<=14;i++){ const v=form.querySelector('select[name="'+i+'"]').value; data[String(i)]=v; } loadData().then(db=>{ const user=localStorage.getItem('jugadorActivo'); if(!user){ alert('Inicia sesión'); return;} db.jornadas[0].pronosticos[user]=data; localStorage.setItem('data_working', JSON.stringify(db)); alert('Pronósticos guardados temporalmente en el navegador. El admin debe exportar para publicar.'); }); }

function renderAciertos(){ loadData().then(db=>{ const out=document.getElementById('aciertos'); if(!out) return; const j=db.jornadas[0]; let html='<table class="pron-table"><thead><tr><th>Jugador</th><th>Aciertos</th></tr></thead><tbody>'; db.players.forEach(p=>{ const a=j.aciertos && j.aciertos[p.username]? j.aciertos[p.username]:0; html+='<tr><td>'+p.username+'</td><td>'+a+'</td></tr>'; }); html+='</tbody></table>'; out.innerHTML=html; }); }

function renderPerfil(){ loadData().then(db=>{ const out=document.getElementById('perfil'); if(!out) return; const user=localStorage.getItem('jugadorActivo'); if(!user){ out.innerHTML='Inicia sesión'; return;} const p=db.players.find(x=>x.username===user); out.innerHTML='<p><strong>'+p.name+'</strong></p><p>Saldo: '+p.saldo+' €</p><p>Aciertos jornada 1: '+(db.jornadas[0].aciertos[user]||0)+'</p>'; }); }

document.addEventListener('DOMContentLoaded', function(){ renderJornadaList(); if(document.getElementById('matches')) renderJornadaById(); if(document.getElementById('mypron')) renderMyPron(); if(document.getElementById('aciertos')) renderAciertos(); if(document.getElementById('perfil')) renderPerfil(); });
